config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('store.urls', 'store'), namespace='store')),
    path('users/', include(('users.urls', 'users'), namespace='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.store , name='store'),
    path('search/', views.search_result, name='search_result'),
    path('/detail/<int:pk>/', views.products_detail, name='products_detail'),
    path('store/<int:pk>/leave-comment', views.leave_comment, name='leave_comment'),
    path('cart/', views.cart, name='cart'),
    path('delete_cart_item/<int:pk>/', views.delete_cart_item, name='delete_cart_item'),
    path('edit_cart/<int:pk>', views.edit_cart_item, name='edit_cart_item'),
    path('orders/', views.orders, name='orders'),
    path('cart/create_order', views.create_order, name='create_order'),
    path('rate_product/<int:pk>', views.rate_product, name='rate_product')
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

store/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User


class Slide(models.Model):
    title = models.CharField(max_length=50)
    img = models.ImageField('rasm')

    def __str__(self):
        return self.title
    






class Products(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=20000)
    slug = models.CharField(max_length=255)
    image = models.ImageField()
    price = models.IntegerField(null=True)
   

    def __str__(self):
        return self.title
        
    def snippet(self):
        return self.description[:30] + '... read more'

    def shorten(self):
        return self.title[:10] + '...'
  

class Comment(models.Model):
    news = models.ForeignKey(Products, on_delete = models.CASCADE, null=True, related_name='comments')
    comment_text = models.TextField('comment', max_length=1000)

    def __str__(self):
        return 'USER'   + self.comment_text

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

class CartItem(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    def total_price(self):
        return self.product.price * self.quantity



class Order(models.Model):
    address = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    total_price = models.IntegerField()

    def __str__(self):
        return 'Order # %s' % (str(self.id))
    
class OrderProduct(models.Model):
    order = models.ForeignKey('store.Order', on_delete=models.CASCADE, related_name='order_products', null=True)
    product = models.ForeignKey('store.Products', on_delete=models.CASCADE)
    amount = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return '%s x%s' % (self.product, self.amount)




RATE_CHOICES = [
    (1, '1 - Trash'),
    (2, '2 - Bad'),
    (3, '3 - Ok'),
    (4, '4 - Good'),
    (5, '5 - Perfect'),
]


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(max_length=3000, blank=True)
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES, null=True)

    def __str__(self):
        return self.user.username

store/forms.py
from django import forms
from .models import Order,Review ,RATE_CHOICES



class OrderForm( forms.Form):
    address = forms.CharField(label='Write your address')
    phone = forms.CharField(label='Write your phone')

    class Meta:
        model = Order
        fields = ['phone', 'address']

class RateForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}), label='Leave your review here')
    rate = forms.ChoiceField(choices=RATE_CHOICES, required=True, label='Rate product from 1 to 5')

    class Meta:
        model = Review
        fields = ('text', 'rate')

store/views.py
from django.shortcuts import render , reverse ,redirect
from .models import Slide,Products,Comment,CartItem,Order,OrderProduct,Review
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.contrib.auth.models import User
from django.conf import settings
User = settings.AUTH_USER_MODEL
from . import forms


def store(request):
    slides = Slide.objects.all()
    products = Products.objects.all()
    product_id = request.GET.get('product')
    
    if product_id:
            product = Products.objects.get(pk=product_id)
            cart_item = CartItem.objects.filter(product=product)
            if not cart_item:
                cart_item = CartItem.objects.create(customer=request.user, product=product, quantity=1)
                cart_item.save()
                return redirect('store:store')
            for item in cart_item:
                item.quantity += 1
                item.save()


    return render(request, 'store.html', {'slides':slides, 'products':products , } )



def products_detail(request, pk):
    product = Products.objects.get(pk=pk)
    return render(request, 'products_detail.html', {'product': product})


def search_result(request):
    query = request.GET.get('search')
    search_obj = Products.objects.filter(Q(title__icontains=query)|Q(description__icontains=query))
    return render(request,'search.html', {'search_obj':search_obj,
    'query':query})


def leave_comment(request,pk):
    try:
        news = Products.objects.get(pk=pk)
    except:
        raise Http404("sahifa error ")
    
    if request.user.is_authenticated:
        news.comments.create( comment_text = request.POST.get ('comment_text'))
    
    else:
        news.comments.create( comment_text= request.POST.get('comment_text'))
        comment = Comment.objects.all()
    return HttpResponseRedirect(reverse('store:products_detail', args = (news.pk,)))




def cart(request):
    cart_items = CartItem.objects.filter(customer=request.user)
    print([item.total_price() for item in cart_items])
    total_price = sum([item.total_price() for item in cart_items])
    total_quantity = sum([item.quantity for item in cart_items])

    return render(request, 'cart.html',{'cart_items': cart_items, 'total_quantity': total_quantity, 'total_price': total_price})


def edit_cart_item(request, pk):
    cart_item = CartItem.objects.get(pk=pk)
    action = request.GET.get('action')

    if action == 'take' and cart_item.quantity > 0:
        if cart_item.quantity == 1:
            cart_item.delete()
            return redirect('store:cart')
        cart_item.quantity -= 1
        cart_item.save()
        return redirect('store:cart')
    cart_item.quantity +=1
    cart_item.save()
    return redirect('store:cart')


def delete_cart_item(request, pk):
    cart_item = CartItem.objects.get(pk=pk)
    cart_item.delete()
    return redirect('store:cart')





def create_order(request):
    cart_items = CartItem.objects.all()
    total_price = sum([item.total_price() for item in cart_items])
    amount = sum([item.quantity for item in cart_items])
    form = forms.OrderForm(request.POST)

    if request.method == 'POST' and form.is_valid():
        order = Order.objects.create(
            address=request.POST.get('address'),
            phone=request.POST.get('phone'),
            total_price=total_price,
            user=request.user
        )
        for cart_item in cart_items:
            OrderProduct.objects.create(
                order=order,
                product=cart_item.product,
                amount=cart_item.quantity,
                total=cart_item.total_price(),
            )

        cart_items.delete()
        return redirect('store:cart')

    form = forms.OrderForm()
    return render(request, 'order_creation_page.html', {
        'cart_items': cart_items,
        'total_price': total_price,
        'amount': amount,
        'form': form})



def orders(request):
    orders_list = Order.objects.filter(user=request.user)
    return render(request, 'orders.html', {'orders': orders_list})


def rate_product(request, pk):
    product = Products.objects.get(pk=pk)
    reviews = Review.objects.filter(product=product)

    if request.method == 'POST':
        form = forms.RateForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            rating.user = request.user
            rating.product = product
            rating.save()
            return redirect('store:rate_product', pk=pk)
    form = forms.RateForm()
    return render(request, 'rate.html', {'form': form, 'product': product, 'reviews': reviews})

store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<style>
    .box{
        width: 100%;
        height: 90px;
        background-color: rgb(27, 24, 49);
    }
</style>
</head>
<body>
   
<div class="box">
        <div class="d-flex" style="align-items: center;"> 
                <img src="{% static 'img/appstorelogo.svg'%}" width="100px" height="100px" alt="">
    <p style="font-size: 20px; color: white;" class=""><b>  Online-store</b></p>
    

<a href=" {% url 'store:cart'%}">  <img src="{% static 'img/korzina.png'%}" style="margin-left: 1200px;" class="p-2 g-col-6" width="100px" height="100px" alt=""></a>   

</div>


</div>


{% block slider %}
{% endblock slider %}


<div> 
    {% for itms in categories %}
    &nbsp; &nbsp;&nbsp;<a href="{{itms.get_absolute_url}}">
    <button class="btn btn-outline-secondary" >{{itms.title}}</button> <br>
    </a><br> 
    {% endfor%} 
    </div> 
    


    {% if user.is_authenticated %}
    <a class="navbar-item order" href="">
    <img src="" width="50px">
    </a>&nbsp;
  </a>
  <a href="{% url 'users:sign_out' %}" class="button is-danger">Выйти</a> &nbsp;
  <a href="" class="button is-light">
      <img src="{{ user.image.url }}" alt="">
      <p class="subtitle is-6 mx-1">{{ user.username }}</p>
  </a>

  <form action="{% url 'store:search_result' %}" method="GET">  
    <input type="text"  name="search" placeholder="Search..." >
    </form>

      {% else %}
    <a href="{% url 'users:sign_up' %}" class="button is-light">
        <p class="subtitle is-6 mx-1">регистрация</p>
    </a>
    <a href="{% url 'users:sign_in' %}" class="button is-light">
        <ion-icon name="person-outline"></ion-icon>
        <p class="subtitle is-6 mx-1">Войты</p>
    </a>
{% endif %}


{% block content%}
{% endblock content %}





<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

store/templates/cart.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="card mb-4 p-4 has-text-weight-bold is-size-4">
            <a class="button has-text-left is-danger" href="{% url 'store:store' %}">Back to main page</a>
            <a href="{% url 'store:create_order' %}">chekout</a>
            <hr>
            <div class="columns has-text-centered">
                <div class="column">
                    <div class="content">Items: {{ total_quantity }}</div>
                </div>
                <div class="column">
                    <div class="content">Total: {{ total_price }} sum</div>
                </div>
            </div>
        </div>
        <div class="card p-5">
            <div class="content">
                <table class="table has-text-centered">
                    <thead>
                    <tr>
                        <th></th>
                        <th>Item</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in cart_items %}
                        <tr>
                            <td>
                                <img src="{{ item.product.image.url }}" alt="" width="100" height="100">
                            </td>
                            <td>{{ item }}</td>
                            <td>{{ item.product.price }} sum</td>
                            <td>
                                {{ item.quantity }}
                                <div class="quantity ml-3">

                                    <a href="{% url 'store:edit_cart_item' item.pk %}?action=add">
                                        <img src="" class="arrows" width="20px" height="20px" alt="add rasmi bulishi kerak">
                                    </a>
                                    
                                      
                                    <a href="{% url 'store:edit_cart_item' item.pk %}?action=take">
                                       <svg xmlns="http://www.w3.org/2000/svg" wid fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"  class="size-2">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 13.5 12 21m0 0-7.5-7.5M12 21V3" />
                                      </svg>
                                    </a>
                                </div>
                            </td>
                            <td>{{ item.total_price }} sum</td>
                            <td>
                                <a href="{% url 'store:delete_cart_item' item.pk %}"
                                   style="font-size: 20px; color: black">
                                    <ion-icon name="trash-outline">del</ion-icon>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

store/templates/category1_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}



<div style="width: 80%;height: 400px ;margin: 0 auto;" class="row row-cols-1 row-cols-md-3 g-10 ">



    {%for produc in categorysr.categor.all%}
    <div style=""  class="col d-flex   "> 
      <div style="border-radius: 8px;padding: 20px;margin-bottom: 20px;box-shadow: 0 2px 4 px rgba(0,0,0,0.1);margin-right: 20px; width: 400px;height: 400px;overflow-wrap: break-word; " class="card bg-dark mt-3"  >
          <img src="{{produc.image.url}}" style="width: 300px;height: 200px; border-radius: 15px;" class="card-img-top" alt="...">
        
        <div style="display: flex;flex-direction: column;" class="card-body ">
          <h5 style="color:white;" class="card-title">{{produc.shorten}}</h5>
          <p style="color:white;" class="card-text">{{produc.snippet}}</p>

          <p style="color:white;" class="card-text">{{produc.price}}$</p>
          <button  class="btn btn-auth"><a style="text-decoration: none;" href="">batafsil</a></button>
  
        </div>
      </div> 
    </div>
  {%endfor%}
   </div>

</div>



{% endblock %} 

store/templates/order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="card p-5">
            <div class="content">
                {% if orders %}
                    <div class="title has-text-centered">My recent orders</div>
                    <table class="table has-text-centered">
                        <thead>
                        <tr>
                            <th>Order number</th>
                            <th>Products</th>
                            <th>Total</th>
                            <th>Status</th>
                            <th>Payed</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in orders %}
                            <tr>
                                <td>{{ order }}</td>
                                <td>
                                    {% for order_product in order.order_products.all %}
                                        <a href="{% url 'store:product_detail' order_product.product.pk %}">
                                            {{ order_product }}
                                        </a>,
                                    {% endfor %}
                                </td>
                                <td>{{ order.total_price }} sum</td>
                                <td>In consideration</td>
                                <td>Not payed</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="title has-text-centered">Nothing ordered yet</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

store/templates/order_creation_page.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <div class="column">
                <div class="box">
                    <form method="post" action="{% url 'store:create_order' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="title">
                            Shipping Information:
                        </div>
                        {% for field in form %}
                            <div class="field">
                                <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit" class="button is-fullwidth is-success">Submit</button>
                    </form>
                </div>
            </div>
            <div class="column is-6">
                <div class="box">
                    <a class="button is-danger" href="{% url 'store:cart' %}">Back to cart</a>
                    <hr>
                    <div class="title">Order Summary</div>
                    <table class="table is-fullwidth">
                        <thead>
                        <tr class="has-text-weight-bold">
                            <td></td>
                            <td>Product</td>
                            <td>Price</td>
                            <td>Quantity</td>
                            <td>Total</td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in cart_items %}
                            <tr>
                                <td>
                                    <img src="{{ item.product.thumb.url }}" alt="" width="50" height="50">
                                </td>
                                <td>{{ item }}</td>
                                <td>{{ item.product.price }} sum</td>
                                <td>x {{ item.quantity }}</td>
                                <td>{{ item.total_price }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="title is-size-4">Total: {{ total_price }} sum </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

store/templates/products_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section">
    <div class="tile is-ancestor is-centered">
        <div class="tile is-parent is-4">
            <div class="box">
                <figure class="image">
                    <img src="{{ product.image.url }}" width="300px" alt="">
                </figure>
            </div>
        </div>
        <div class="tile is-parent is-vertical">
            <div class="tile is-child">
                <div class="box">
                    <h1 class="title">
                        {{ product.title }}
                    </h1>
                    <hr>
                    <p class="subtitle is-6">
                        {{ product.description }}
                    </p>
                    <h1 class="title mt-1 is-4">{{ product.price }}$</h1>
                    <p class="subtitle mt-1 is-6">Количество:</p>
                    <div class="level">
                        <div class="level-right">
                            <div class="level-item">
                                <button id="minus" class="button is-rounded is-small" onclick="minus()">–</button>
                            </div>
                            <div class="level-item">
                                <form action="" id="order">
                                    <input type="text" class="input" value="0" name="count">

                                    <button type="submit" class="button is-info">Оформить заказ</button>
                                </form>
                            </div>
                            <div class="level-item">
                                <button id="plus" class="button is-rounded is-small" onclick="plus()">+</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <a href="{% url 'store:rate_product' product.pk  %}" style="text-decoration: none;color: white ;"  >Rate</a>

    <form class="form" action="{% url 'store:leave_comment' product.pk %}" method="POST">
            
        {% csrf_token %}
            <textarea style="width: 170px;height: 45px;" class="textarea" id="comment" name="comment_text" cols="10" rows="1" aria-required="true" placeholder="Оставьте комментарий"></textarea>
            <br><br>
            <button class="btn btn-primary" type="submit" >commentni qo'shish</button>
            
            {% for comment in product.comments.all %}
                <p style="margin-left: 6px;margin-top: 30px;" class=""><i>{{comment.author}} </i>{{comment.comment_text}}</p> <hr>
            {% endfor %}
        </form>

       

</section>

    <script>
        let form = document.querySelector('#order')
        let minusButton = document.querySelector('#minus')

        function plus (){
            form.count.value++
            minusButton.removeAttribute('disabled')
        }

        function minus() {
            if (form.count.value > 0) {
                form.count.value--
            } else {
                minusButton.setAttribute('disabled', '')
            }
        }
    </script>
{% endblock %}

store/templates/rate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="section">
        <div class="columns is-flex is-align-items-center">
            <div class="column">
                <div class="box">
                    <figure class="image product-detail-image">
                        <img src="{{ product.thumb.url }}" alt="Placeholder image">
                    </figure>
                </div>
            </div>
            <div class="column">
                <div class="box">
                    <div class="content">
                        <p class="title is-size-2">
                            {{ product.title }}
                            {% if product.is_new %}
                                <span class="tag is-danger">New!</span>
                            {% endif %}
                            {% if product.is_discounted %}
                                <span class="tag is-primary">Discount!</span>
                            {% endif %}
                        </p>
                        <p class="title is-size-5 has-text-grey-light">{{ product.description }}</p>
                        <form action="{% url 'store:rate_product' product.pk %}" method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if field.name == 'rate' %}
                                    <div class="select is-fullwidth my-2">
                                        <label for="{{ field.id_for_label }}"
                                               class="label is-size-4">{{ field.label }}</label>
                                        {{ field }}
                                    </div>
                                {% else %}
                                    <div class="field">
                                        <label for="{{ field.id_for_label }}" class="label is-size-4">
                                            {{ field.label }}
                                        </label>
                                        {{ field }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <div class="mt-6">
                                <button class='button is-success' type="submit">Submit</button>
                                <a class='button is-danger' href="{% url 'store:products_detail' product.pk %}">
                                    Back to {{ product.title }}</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="section">
            {% if reviews %}
                <div class="title is-size-3 has-text-centered">Reviews of other clients</div>
                <div class="columns is is-multiline is-centered">
                    {% for review in reviews %}
                        <div class="column is-6">
                            <div class="card">
                                <div class="card-content">
                                    <p class="subtitle has-text-right has-text-grey-light is-6">{{ review.date }}</p>
                                    <div class="media">
                                        <div class="media-left">
                                            <figure class="image is-48x48">
                                                <img src="https://bulma.io/images/placeholders/96x96.png"
                                                     alt="Placeholder image" class="is-rounded">
                                            </figure>
                                        </div>
                                        <div class="media-content">
                                            <p class="title is-4">{{ review.user.first_name }}</p>
                                            <p class="subtitle is-6">@{{ review.user.username }}</p>

                                        </div>
                                    </div>
                                    <div class="content is-size-5 has-text-weight-bold has-text-centered">
                                        {{ review.text }}
                                    </div>
                                    <p class="subtitle is-size-4">
                                        <ion-icon name="star-outline"></ion-icon>
                                        {{ review.rate }} out of 5
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="title is-size-3 has-text-centered">No reviews yet. Be first to leave one</div>
            {% endif %}
        </div>
        <hr>
    </div>
{% endblock %}

store/templates/search.html
{% extends 'base.html' %}


{% block content%}



<div class="card">
  {% for post in search_obj%}
  <a href="{% url 'store:products_detail' post.pk%}" style="color: black;" > 

  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4">{{post.title}}</p>
        <p>{{post.description}}</p> <br>
        <span class="is-flex ">
        
        </span>
      
        
      </div>
      <div class="media-left">
        <figure class="image is-10x10">
          <img src="{{post.image.url}}" style="width: 200px; height:200px;" alt="Placeholder image">
        </figure>
      </div>
    
    </div>

   
      <br>
    </a> 
     <hr>
  </div>  
  {% endfor %} 
</div>
{% endblock %}